[[section-system-scope-and-context]]
== Alcance y contexto del sistema

[role="arc42help"]
****
.Contents
Nuestro proyecto consistirá en realizar una aplicación web mediante la cual podremos geolocalizar a nuestros amigos cercanos.

Las tecnologías que utilizaremos seran principalmente: SOLID como estrategia para el manejo de datos y REACT para el desarrollo de las interfaces de usuario.

.Motivation

.Form

****


=== Business Context

[role="arc42help"]
****
.Contents
Nuestra aplicación se basará en una aplicación web, esta aplicación tendrá la funcionalidad de un radar, el cual mostrará a los amigos cercanos de dicho usuario, la distancia hasta la cual podremos detectar amigos sera definida por el propio usuario. Dichos amigos apareceran en un mapa pudiendo ver claramente su posicion respecto a donde nos encontramos.

.Motivation
La principal funcionalidad de la aplicacion será agregar y eliminar amigos para poder observar su localización, además de esto el usuario podrá registrar su información personal.

.Form
*Se agregará un pequeño esquema*
****


=== Technical Context

[role="arc42help"]
****
.Contents
Esta aplicación se basara en diversas tecnologías, las más importantes son SOLID y REACT.

Mediante los principios SOLID nuestra aplicacion será descentralizada lo que nos permitirá obtener información sin tener que realizar peticiones a un servidor centralizado.

REACT es una biblioteca Javascript de código abierto con la cual podremos realizar las interfaces de usuario para nuestra aplicación de forma sencilla.

.Motivation

.Form

****
