[[section-solution-strategy]]
== Estrategia de solución

=== Decisiones tecnológicas
A la hora de crear la aplicación, la primera decisión que se tomó fue la de usar el lenguaje JavaScript, ya que es un lenguaje con una sintáxis fácil de entender
para todos los integrantes del grupo y para así aprovechar el Framework React.js, lo que nos permitiría crear la aplicación web de una manera muy sencilla. Además,
es una plataforma de código abierto con muchos tutoriales y facilidad para desarrollar el front-end de una app web.

Otro punto a destacar es el uso de la tecnología SOLID, ya que gracias a los POD´s cada usuario es propietario de sus datos.

De cara a otros elementos menos orientados a la app, usaremos Gir como sistema de control de versiones y el modelo Arc42 para documentar.

==== Tecnologias empleadas
* JavaScript como lenguaje de programación de la aplicación.
* React para facilitar el desarrollo del front-end.
*  https://github.com/solid/react-components[solid-react] que nos permite realizar el Login.
* https://github.com/solid/solid-auth-client[Solid-auth-client] para la autentificación con SOLID.
* MongoDB para almacenar los datos requeridos por el servidor.
* Express para la restApi.
* https://vincenttunru.gitlab.io/tripledoc/[tripledoc] para obtener diferentes datos de los POD´s.
* https://github.com/google-map-react/google-map-react[react-google-maps] que nos permite utilizar el mapa para mostrar los diferentes usuarios. 
* https://github.com/shukerullah/react-geocode[react-geocode] para traducir coordenadas en ubicaciones con nombre.
* https://jestjs.io/es-ES/[JEST] Para testing tanto de la restApi como de la webApp
* https://reactrouter.com/web/guides/quick-start[react-router-dom] Permite navegar por las diferentes vistas de nuestra página.
* Graphana y Prometheus para la monitorización.
* https://dashboard.heroku.com/login[Heroku]para el despliegue de nuestra aplicación.



=== Decisiones relacionadas con los objetivos de calidad
Para cumplir diferentes objetivos de calidad hemos decidido realizar diferentes acciones.

* *Privacidad:* Para cumplir este objetivo hemos decidido guardar la menor información posible del usuario en nuestro servidor, con esta premisa finalmente guardamos todas las ubicaciones del usuario en su propio POD estando éstas a en su poder.
* *Usabilidad:* Nuestra interfaz es bastante simple e intutitiva de forma que tendremos unicamente 3 elementos diferenciados: 
    ** Lista de amigos: Podremos ver nuestros amigos cercanos, lejanos y desconectados.
    ** Mapa: Un simple mapa donde podemos ver a nuestros amigos están su webID de solid en los marcadores además de nuestro radio marcado.
    ** Historial de ubicaciones: Podemos ver una lista de nuestras ubicaciones, con el dia, hora y nombre reflejados, pudiendo eliminarlas de un simple click.

* *Funcionalidad:* Nos ha parecido clave dar al usuario el manejo de sus ubicaciones en el POD para poder este tener información de sus movimientos.
* *Rendimiento:* Debido al lento (e inestable) acceso al POD, la última ubicación de los usuarios se guarda en la base de datos Mongo para hacer más rápido el acceso a estas. Además en el caso de que la ubicación no varíe en un número de metros, esta no será enviada ni al servidor ni al POD.
* *Testeabilidad:* Disponemos de un gran numero de pruebas de la restApi para asegurarnos de su correcto funcionamiento, por otro lado, las pruebas de la webApp no han sido tan exahustivas debido a la dependencia que tenemos de SOLID en los distintos componentes.

=== Organización
Mantenemos reuniones semanales para hablar de los problemas y metas para la siguiente semana creando un acta de la reunión. 
Punto importante que afectará al proyecto debido a ser solo 3 personas las que desarrollan la aplicación.

