[[section-deployment-view]]


== Vista de despliegue

Como ya hemos visto, el radarín en ejecución se compone de 4 bloques de software que interacúan entre sí, la webapp, restapi, pod de SOLID y mongoDB. Aquí veremos el entorno de ejecución para estos componentes en desarollo y el despliegue.

La webapp, desarrollada con react, es una aplicación web que se ejecutar en el navegador del cliente, y accede al pod de SOLID y a la restapi mediante peticiones http. En producción usamos el servidor web express para enviar los archivos estáticos de la web al cliente, que habrán sido generados previamente con un build optimizado de la aplicación react.

En cuanto al pod de SOLD no tenemos que preocuparnos en el despliegue, ya que usamos los pods de otros proveedores como "solidcommunity" o "inrupt".

Para ejecutar la restapi simplemnte tenemos que lanzar el servidor express, que accederá a la base de datos mongo mediante el protocolo mongodb.

La base de datos de producción esta en mongo cloud, por lo que, una vez configurada, solo tenemos que añadir las credenciales de acceso a la restapi.

La elección de la base de datos mongo cloud se ha basado principalmente en el bajo coste (versión gratutía). Además mongo cloud nos ofrece una capacidad de almacenamiento de sobra para nuestras necesidades, y una muy buena estabilidad de rendimiento.

image::DeploymentDiagram.svg[DeploymentDiagram]

=== Infraestructura de despliegue

Visto esto, solo tenemos que preocuparnos por desplegar la webapp y restapi cada vez que actualicemos la versión de la aplicación. Estos dos bloques se despliegan en Heroku, cada uno en un Dyno (nombre que le da Heroku a cada máquina para ejecutar una aplicación). Para configurar cada aplicación (webapp y restapi) en Heroku usamos docker. De esta forma indicamos a Heroku como debe ejecutar cada aplicación, y en que entorno.

Hemos escogido Heroku como entorno para desplegar el sistema por su versión gratutía, que aunque nos ofrece unos recursos muy limitados, son suficientes para nuestra aplicación y el reducido número de usuarios que esperamos inicialmente.

Además de lo anterior, también tenemos un sistema de monitorización con prometheus y grafana corriendo en una instancia en AWS. Este hace peticiones http a la restapi para pedir información sobre el estado del servidor. En esta máquina de AWS también tenemos un servidor web para que el administrador pueda consultar los datos de la monitorización de forma sencilla.

En este caso hemos elegido ejecutar la monitorización en AWS por simplicidad, ya que Heroku no nos permite lanzar más de una aplicación en cada Dyno. Nos resultaba mas sencillo usar AWS por la gran flexibilidad que nos ofrece en comparación a Heroku.