== 8. Conceptos
=== Conceptos transversales

==== 8.1 Seguridad
****
La seguridad en nuestra aplicación se basará en el uso de SOLID, por lo que cada usuario tendrá su propio POD y será él el que otorgue los permisos a las aplicaciones que él quiera.

Cada usuario posee una contraseña propia para acceder a la restapi evitando asi que otros usuarios puedan suplantar su identidad pudiendo por ejemplo modificar y observar ubicaciones a las que no deben tener acceso.

Para poder observar las ubicaciones de un usuario estos deben estar mutuamente agregados evitando que puedan observarse localizaciones usuarios a los que no se les ha permitido.
****

==== 8.2 Persistencia
****
Debido a la utilización de SOLID, no será necesario contar con una base de datos, sino que será el mismo usuario el que almacene sus datos.
****

==== 8.3 Interfaz de usuario
****
La aplicación contará con una interfaz de usuario para que el usuario sea capaz de utilizar toda la implementación de la misma. Dicha interfaz se desarrollará con React como complementación a JavaScript.
****

==== 8.4 Manejo de errores
****
La aplicación informará al usuario de los errores que vayan ocurriendo.
****

==== 8.5 Pruebas
****
La aplicación será sometida a casos de prueba para comprobar la eficiencia de la misma.
****
